################################################################################
#                                                                              #
#    Author: Serguei Nastassi          itoracle@icloud.com                     #
#    Created 01/03/2023                                                        #            
################################################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: oracle-rac-213
  labels:
    kubernetes.io/metadata.name: oracle-rac-213
#    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
#    pod-security.kubernetes.io/warn: privileged
spec:
  finalizers:
  - kubernetes
