################################################################################
#                                                                              #
#    Author: Serguei Nastassi          itoracle@icloud.com                     #
#    Created 01/03/2023                                                        #            
################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: rdbms-tcp
  labels:
    app: rdbms-tcp
spec:
 ports:
 - protocol: TCP
   port: 1521
   targetPort: oracle-listener
 selector:
   app: oracle-rac-213
 type: NodePort